### ISSUE TITLE
json convention 

### ISSUE THREAD

**Issue by rigelrozanski** [kossmar/price-parser#21]
https://github.com/kossmar/price-parser/blob/5f019e81db7dcaebc18bbfb2c1cf54749ae99332/cmd/price-parser.go#L22-L30

json convention is to use under_scores and not CamelCase 
aka rename json comments from something like `lowestAsk` to `lowest_ask`

I know it's confusing because golang uses camelcase everywhere, but it's the convention

**Comment by kossmar** [comment]
What do the comments do? I thought I was supposed to be mimicking the string keys in the json file?

**Comment by rigelrozanski** [comment]
it is the key string in the json file... which should use json convention aka `lower_ask`
