### ISSUE TITLE
dead functions?

### ISSUE THREAD

**Issue by rigelrozanski** [kossmar/price-parser#27]
https://github.com/kossmar/price-parser/blob/5f019e81db7dcaebc18bbfb2c1cf54749ae99332/cmd/price-parser.go#L137

Looks like this function isn't used

**Comment by kossmar** [comment]
Don't know why I wasn't using that. That sets up the output file. I asked you this following question on FB but you say you're on here all the time so :
What is a good way to setup a generic output file path?
Currently the output file path is specific to my computer so it wouldn't work on someone else's if they installed my program.

**Comment by rigelrozanski** [comment]
... use root directory
