### ISSUE TITLE
Return Errors

### ISSUE THREAD

**Issue by rigelrozanski** [kossmar/price-parser#29]
https://github.com/kossmar/price-parser/blob/5f019e81db7dcaebc18bbfb2c1cf54749ae99332/cmd/price-parser.go#L154

For your program, you should eliminate all use of `panic(error)` function... instead make all your functions return an error if needed (checkout making your functions return two things if you don't already understand how to do that, aka your function can return a string, and an error term (which may end up just being nil) right).. okay and at the very end, you will just return an error from your command function if it is the `RunE` type... see my other github issue

**Comment by kossmar** [comment]
I changed my program up while making it dynamic and didn't add the functions that I was using in my Flag switch statement. I made the functions to make the command block easier on the eyes but I only use the functions once. Should I add them back in or no?

**Comment by kossmar** [comment]
Also when I add the errors to each function as way you described, should I immediately print the error or return as the command function's error?

**Comment by rigelrozanski** [comment]
yeah well if there is a function in a child function then yes return the error immediately, all the way up to the `RunE` function where you also immediately return the error when it's received... its quite a few `if err != nil { return err }` statements which isn't the prettiest but it's the best way to do it
